### ISSUE TITLE
Bug: Ti60F225_person_detect_demo_lite 

### ISSUE THREAD

**Issue by smtalds** [Efinix-Inc/tinyml#1]
tinyml_vision/Ti60F225_person_detect_demo_lite
in this demo, when  I try to configure IP I get version conflict error.
```
Thu July 28 22 15:01:41 - IP ERROR 2: Exception calling application: Cannot find VLNV(vendor='efinixinc.com', library='soc', name='efx_soc', version='2.1') in the IP library, on path E:/Efinity/tutorial/tinyml-main/tinyml_vision/Ti60F225_person_detect_demo_lite/ip/SapphireSoc/settings.json
```

The version Sapphire IP of demo and last released IP version doesn't match.

**Comment by yhlee-efx** [comment]
It seems that you are using the Efinity IDE without patch or without the latest patch. Please install the latest Efinity 2021.2 software patch for the latest Sapphire IP update and the error will go away then.
