### ISSUE TITLE
Custom Instruction

### ISSUE THREAD

**Issue by smtalds** [Efinix-Inc/tinyml#2]
Hi, I am working on `Ti60F225_person_detect_demo_lite`. While trying to understand the working accelerator of the tinyml ,  I need to research custom instructions.  I researched _Sapphire RISC-V User Guide_ and `customInstructionDemo` . RISC-V  includes a custom instruction interface with 1,024 IDs to perform different functions. However, these functions are not specified. Can you publish a file about what these functions are and how do they work?

**Comment by yhlee-efx** [comment]
The RTL of the custom instruction demo module i.e., _custom_instruction_tea_, is provided in the _design_modules.v_ file. You may refer to the source code for more details.
